In [77]:
import pandas as pd

In [78]:

#Questão 1
data1= [{'leonardo':5.4, 'nicolas':11.99, 'alisson':4.5, 'adriano':6.0, 'gustavo':8.3}]
df1= pd.DataFrame(data1)
df1

   leonardo  nicolas  alisson  adriano  gustavo
0       5.4    11.99      4.5      6.0      8.3

In [79]:
# QUestão 2

data2= [{'nome': 'ana', 'cargo': 'analista'},{'nome': 'bruno', 'cargo': 'gerente', 'bonus': 500}]
df2= pd.DataFrame(data2)
df2

# Ana esta com  o valor NAN em "bonus", porque a coluna "bonus" foi 
# adicionada no segundo dicionario mas não no primeiro, que e aonde ana é representada
# por isso, o valor ficou ausente e foi preenchido por NAN (Not a Number).

    nome     cargo  bonus
0    ana  analista    NaN
1  bruno   gerente  500.0

In [80]:
# QUestão 3 

data3= {'nome': pd.Series(['maçã','banana', 'uva'], index= ['p1', 'p2', 'p3']),
        'preços': pd.Series(['R$10,50', 'R$5,90', 'R$2,45'], index= ['p1', 'p2', 'p3'])}
df3= pd.DataFrame(data3)
df3

      nome   preços
p1    maçã  R$10,50
p2  banana   R$5,90
p3     uva   R$2,45

In [81]:
# Questão 4

data4= [{'Sede_A':2500, 'Sede_B':3700}]
df4= pd.DataFrame(data4)
df4 ['Total_Vendas']= df4['Sede_A']+df4['Sede_B']
df4 ['Imposto']= df4['Sede_A'] * 10/100
df4

   Sede_A  Sede_B  Total_Vendas  Imposto
0    2500    3700          6200    250.0

In [82]:
# ----------------Questão 5----------------

data5= {'Clientes': pd.Series(['sergio','paulo', 'lucas']),
        'CPF': pd.Series(['154.877.990-32', '677.635.400-60', '308.142.040-74']),
        'Telefone': pd.Series(['9532539680', '2830961338', '3424936280'])}
df5 = pd.DataFrame(data5)
df5

  Clientes             CPF    Telefone
0   sergio  154.877.990-32  9532539680
1    paulo  677.635.400-60  2830961338
2    lucas  308.142.040-74  3424936280

In [83]:
# Excluindo a coluna "CPF" utilisando o comando del.

del df5['CPF']
df5

  Clientes    Telefone
0   sergio  9532539680
1    paulo  2830961338
2    lucas  3424936280

In [84]:
# Excluindo a coluna "Telefone" usando o método pop()

df5.pop('Telefone')
df5
# ----------------FIM questão 5 ----------------

  Clientes
0   sergio
1    paulo
2    lucas

In [85]:
#----------------Questão 6----------------

data6= {'Área': pd.Series(['8.515.767 km²','2.780.400 km²', '756.102 km²'], index=['Brasil', 'Argentina', 'Chile']),
        'População': pd.Series(['203.062.512', '46.234.830', '19.629.590'], index=['Brasil', 'Argentina', 'Chile']),
        'Telefone': pd.Series(['33 anos', '32 anos', '35 anos'], index=['Brasil', 'Argentina', 'Chile'])}
df6= pd.DataFrame(data6)
df6

                    Área    População Telefone
Brasil     8.515.767 km²  203.062.512  33 anos
Argentina  2.780.400 km²   46.234.830  32 anos
Chile        756.102 km²   19.629.590  35 anos

In [86]:
# Utilisando o método loc para
# recuperar e imprimir apenas os dados referentes ao ’Brasil’.

df6 = pd.DataFrame(df6)
print (df6.loc['Brasil'])

# ----------------FIM questão 6 ----------------

Área         8.515.767 km²
População      203.062.512
Telefone           33 anos
Name: Brasil, dtype: object

In [87]:
#----------------Questão 7---------------- 

data7= {'Tabela FIPE': pd.Series(['R$152.223', 'R$132.798', 'R$140.739', 'R$1.052.956', 'R$112.081', 'R$82.478'], index=['Toyota Corolla', 'BYD Dolphin', 'Jeep Compass', 'Porsche 911', 'Fiat Fastback', 'Hyundai HB20']),
        'Concessionaria': pd.Series(['R$165.900', 'R$146.900', 'R$156.900', 'R$1.150.000+', 'R$ 119.990', 'R$ 95.190'], index=['Toyota Corolla', 'BYD Dolphin', 'Jeep Compass', 'Porsche 911', 'Fiat Fastback', 'Hyundai HB20'])}
df7= pd.DataFrame(data7)
df7

                Tabela FIPE Concessionaria
Toyota Corolla    R$152.223      R$165.900
BYD Dolphin       R$132.798      R$146.900
Jeep Compass      R$140.739      R$156.900
Porsche 911     R$1.052.956   R$1.150.000+
Fiat Fastback     R$112.081     R$ 119.990
Hyundai HB20       R$82.478      R$ 95.190

In [88]:
# Utilizando o comando "iloc" para selecionar e exibir
# os dados do quarto e quinto carro.

print ( df7.iloc[3:5])

# ----------------FIM questão 7 ----------------

               Tabela FIPE Concessionaria
Porsche 911    R$1.052.956   R$1.150.000+
Fiat Fastback    R$112.081     R$ 119.990

In [89]:
# ----------------FIM questão 8 ----------------

data8 = {
    'Data': pd.Series([
        '2026-03-01', '2026-03-02', '2026-03-03', '2026-03-04', '2026-03-05',
        '2026-03-06', '2026-03-07', '2026-03-08', '2026-03-09', '2026-03-10',
        '2026-03-11', '2026-03-12', '2026-03-13', '2026-03-14', '2026-03-15',
        '2026-03-16', '2026-03-17', '2026-03-18', '2026-03-19', '2026-03-20'
    ], index=[f'Sensor{i}' for i in range(1, 21)]),

    'Temperatura': pd.Series([
        22.5, 23.1, 22.8, 24.0, 25.2, 23.9, 22.1, 21.8, 23.5, 24.1,
        22.9, 23.3, 24.5, 25.0, 23.7, 22.4, 21.9, 23.0, 24.8, 25.5
    ], index=[f'Sensor{i}' for i in range(1, 21)]),

    'Status': pd.Series([
        'OK', 'OK', 'Alerta', 'OK', 'Critico', 'OK', 'OK', 'OK', 'OK', 'Alerta',
        'OK', 'OK', 'Critico', 'OK', 'OK', 'OK', 'OK', 'Alerta', 'OK', 'Critico'
    ], index=[f'Sensor{i}' for i in range(1, 21)])
}

# 2. Convertendo o dicionário para DataFrame
df8 = pd.DataFrame(data8)
df8

                Data  Temperatura   Status
Sensor1   2026-03-01         22.5       OK
Sensor2   2026-03-02         23.1       OK
Sensor3   2026-03-03         22.8   Alerta
Sensor4   2026-03-04         24.0       OK
Sensor5   2026-03-05         25.2  Critico
Sensor6   2026-03-06         23.9       OK
Sensor7   2026-03-07         22.1       OK
Sensor8   2026-03-08         21.8       OK
Sensor9   2026-03-09         23.5       OK
Sensor10  2026-03-10         24.1   Alerta
Sensor11  2026-03-11         22.9       OK
Sensor12  2026-03-12         23.3       OK
Sensor13  2026-03-13         24.5  Critico
Sensor14  2026-03-14         25.0       OK
Sensor15  2026-03-15         23.7       OK
Sensor16  2026-03-16         22.4       OK
Sensor17  2026-03-17         21.9       OK
Sensor18  2026-03-18         23.0   Alerta
Sensor19  2026-03-19         24.8       OK
Sensor20  2026-03-20         25.5  Critico

In [90]:
# Utilisando o operador Slicing (Dois Pontos) para extrair e exibir 
# um novo DataFrame contendo apenas da 5° até a 12° linha do DataFrame original

dt8= (df8[4:12])
dt8

# ----------------FIM questão 8 ----------------

                Data  Temperatura   Status
Sensor5   2026-03-05         25.2  Critico
Sensor6   2026-03-06         23.9       OK
Sensor7   2026-03-07         22.1       OK
Sensor8   2026-03-08         21.8       OK
Sensor9   2026-03-09         23.5       OK
Sensor10  2026-03-10         24.1   Alerta
Sensor11  2026-03-11         22.9       OK
Sensor12  2026-03-12         23.3       OK

In [ ]:
# ----------------FIM questão 9 ----------------

data_loja1 = {
    'Produto': pd.Series(['Smartphone', 'Tablet', 'Notebook', 'Impressora', 'Roteador'], index=[1, 2, 3, 4, 5]),
    'Estoque': pd.Series([12, 8, 5, 10, 20], index=[1, 2, 3, 4, 5])
}
df_loja1 = pd.DataFrame(data_loja1)

data_loja2 = {
    'Produto': pd.Series(['Cadeira Gamer', 'Mesa Office', 'Luminária', 'Nobreak', 'Monitor Curvo'], index=[1, 2, 3, 4, 5]),
    'Estoque': pd.Series([7, 4, 15, 6, 9], index=[1, 2, 3, 4, 5])
}
df_loja2 = pd.DataFrame(data_loja2)

print(df_loja1)
print("\n")
print(df_loja2)

      Produto  Estoque
1  Smartphone       12
2      Tablet        8
3    Notebook        5
4  Impressora       10
5    Roteador       20


         Produto  Estoque
1  Cadeira Gamer        7
2    Mesa Office        4
3      Luminária       15
4        Nobreak        6
5  Monitor Curvo        9

In [ ]:
# Adicionando asinformações da loja2 ao final da loja1.

df_loja1= pd.concat([df_loja1, df_loja2])
print (df_loja1)

# ----------------FIM questão 9 ----------------

         Produto  Estoque
1     Smartphone       12
2         Tablet        8
3       Notebook        5
4     Impressora       10
5       Roteador       20
1  Cadeira Gamer        7
2    Mesa Office        4
3      Luminária       15
4        Nobreak        6
5  Monitor Curvo        9

In [93]:
# ----------------FIM questão 10 ----------------

data10= {'Funcionarios': pd.Series([
            'Ana', 'João', 'Maria', 'Pedro'
            ], index= [f'Funcionario{i}' for i in range(0, 4)]), 

        'Salario':pd.Series([
            1500., 1250., 2500., 2350.
            ], index= [f'Funcionario{i}' for i in range(0, 4)])
}

df10= pd.DataFrame(data10)
df10

             Funcionarios  Salario
Funcionario0          Ana   1500.0
Funcionario1         João   1250.0
Funcionario2        Maria   2500.0
Funcionario3        Pedro   2350.0